# Server Config
server:
  port: ${SERVER_PORT:8888}
# Spring Config
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  profiles:
    active: ${ENV:dev}

# MyBatis Config
mybatis:
  mapper-locations: classpath:/mappers/*.xml

