# Server Config
server:
  port: 8800
# Spring Config
spring:
  datasource:
    driver-class-name:
    hikari:
      schema: classpath:db/schema-h2.sql
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:h2
      username: root
      password: 123

# MyBatis Config
mybatis:
  type-aliases-package: cloud.ffeng.user.infra.dal.dao
  mapper-locations: classpath:/mybatis/*.xml

